export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_TYPE = 'GET_PRODUCTS_BY_TYPE';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SETUP_ORDER = 'SETUP_ORDER';
